export const ERROR_CODES = {
    ERR_INTERNAL_SERVER_ERROR: 'ERR_INTERNAL_SERVER_ERROR',
    ERR_INVALID_INPUT: 'ERR_INVALID_INPUT',
    ERR_NOT_FOUND: 'ERR_NOT_FOUND',
    ERR_BAD_REQUEST: 'ERR_BAD_REQUEST',
    ERR_INVALID_SLOTSIZE: 'ERR_INVALID_SLOTSIZE',
    ERR_INVALID_TIMESTAMP: 'ERR_INVALID_TIMESTAMP',
    SUCCESS: 'SUCCESS',
};

export const ERROR_MESSAGES = {
    ERR_INTERNAL_SERVER_ERROR: 'ERR_INTERNAL_SERVER_ERROR',
    ERR_INVALID_INPUT: 'ERR_INVALID_INPUT',
    ERR_NOT_FOUND: 'ERR_NOT_FOUND',
    ERR_INVALID_SLOTSIZE: 'ERR_INVALID_SLOTSIZE',
    ERR_BAD_REQUEST: 'ERR_BAD_REQUEST',
    ERR_INVALID_TIMESTAMP: 'ERR_INVALID_TIMESTAMP',
    SUCCESS: 'SUCCESS',
};

export default {
    ERROR_CODES,
    ERROR_MESSAGES,
};